runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /upload.php
  script: www/upload.php

- url: /css
  static_dir: www/css

- url: /demo.html
  static_files: www/demo.html
  upload: www/demo.html

- url: /exp.html
  static_files: www/exp.html
  upload: www/exp.html

- url: /js
  static_dir: www/js

- url: /images
  static_dir: www/images
  
