runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /stage0.html
  static_files: www/stage0.html
  upload: www/stage0.html

- url: /stage1.html
  static_files: www/stage1.html
  upload: www/stage1.html

- url: /stage2.html
  static_files: www/stage2.html
  upload: www/stage2.html

- url: /stage3.html
  static_files: www/stage3.html
  upload: www/stage3.html

- url: /stage4.html
  static_files: www/stage4.html
  upload: www/stage4.html

- url: /end.html
  static_files: www/end.html
  upload: www/end.html

- url: /upload.php
  script: www/upload.php

- url: /css
  static_dir: www/css

- url: /js
  static_dir: www/js

- url: /images
  static_dir: www/images

- url: /scripts
  static_dir: www/scripts
  
